旧账号关联微信登录
EasyAbp/WeChatManagement pull request #50
Opened 2022-09-02 03:01 UTC by blackWins

1. 增加绑定码过期设置`BindCodeExpiredTime`，默认60秒。

3. 添加获取绑定小程序码方法 `GetPcBindACodeAsync`。
4. 添加pc获取绑定状态方法 `GetBindingStatusAsync`。
5.  提取 `UnbindAsync` 中移除现有关联记录代码创建私有方法 `RemoveCurrentBindRelationshipAsync`。
6. 重写 `BindAsync` 方法：
1.允许匿名访问。
2.增加入参 `Token` 绑定标识属性，并强制检测Token有效性。
3.增加入参 `ForceBinding` 强制绑定属性， `true` 可强制解绑现有关联。
4.校验通过移除微信当前关联信息 `RemoveCurrentBindRelationshipAsync` 。
7.写入新的关联。
8.消费 `Token`

2022-09-02 09:18 UTC, gdlcf88 requested changes
文档中的链接最好使用相对路径

2022-09-02 09:18 UTC, gdlcf88 commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Application/EasyAbp/WeChatManagement/MiniPrograms/Login/LoginAppService.cs
> +        public virtual async Task<BindingStatusDto> GetBindingStatusAsync(GetBindingStatusInput input)
`GetBindingStatusAsync`应只实现“查询当前用户绑定状态”的单一职能，不可能有Cache等操作。若调整后此方法无用途，应移除。

2022-09-02 09:18 UTC, gdlcf88 commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Application/EasyAbp/WeChatManagement/MiniPrograms/MiniProgramsApplicationAutoMapperProfile.cs
> +            CreateMap<UserInfo, UserInfoDto>(MemberList.None);
还原DTO改动后记得还原此改动。

2022-09-02 09:18 UTC, gdlcf88 commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Application.Contracts/EasyAbp/WeChatManagement/MiniPrograms/UserInfos/Dtos/UserInfoDto.cs
> +        public string UserName { get; set; }
请移除，由客户端自行获取。

2022-09-02 09:18 UTC, gdlcf88 commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Application/EasyAbp/WeChatManagement/MiniPrograms/UserInfos/UserInfoAppService.cs
> +        public override async Task<PagedResultDto<UserInfoDto>> GetListAsync(PagedAndSortedResultRequestDto input)
此处可以拿到IdentityUser仓储为对IdentityServer模块的错误引入导致。实际上`EasyAbp.WeChatManagement.MiniPrograms.Domain`应拆分为`EasyAbp.WeChatManagement.MiniPrograms.Domain`和`EasyAbp.WeChatManagement.MiniPrograms.Domain.Identity`。此模块将在ABP 6.0弃用IDS4重做。

参考[WeChatAppUserAppService.cs](https://github.com/EasyAbp/WeChatManagement/pull/50/files#diff-db2684dc9bd4bee72a5f46ee293dc5f3cc9a02f193f729b22535dc62a9de7579)的问题，此文件应还原。

2022-09-02 09:18 UTC, gdlcf88 commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Domain/EasyAbp/WeChatManagement/MiniPrograms/Settings/MiniProgramsSettings.cs
> +            public const string BindCodeExpiredTime = PcLoginGroupName + ".BindCodeExpiredTime";
使用命名解决歧义：`BindCodeExpiredInSeconds`。

替换后请检查是否有遗漏，避免“阴阳命名”。

2022-09-02 09:18 UTC, gdlcf88 commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Web/Pages/WeChatManagement/MiniPrograms/UserInfos/UserInfo/index.js
> +            { data: "userName", orderable: false },
与PR无关。请还原此文件，如有意迭代模块MVC配套前端，须在新PR进行。

2022-09-02 09:32 UTC, blackWins commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Application/EasyAbp/WeChatManagement/MiniPrograms/Login/LoginAppService.cs
> +            if (await _identityUserManager.FindByLoginAsync(loginResult.LoginProvider, loginResult.ProviderKey) == null) return;
此处通过登录尝试检查是否存在关联用户，如存在则执行后续移除操作，否则直接退出当前方法。

2022-09-02 09:36 UTC, gdlcf88 commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Application/EasyAbp/WeChatManagement/MiniPrograms/Login/LoginAppService.cs
> +            if (await _identityUserManager.FindByLoginAsync(loginResult.LoginProvider, loginResult.ProviderKey) == null) return;
Remove是需要成功的，如果没有关联用户，应抛出错误。这就是为什么不能在此方法中使用Find。另请结合https://github.com/EasyAbp/WeChatManagement/pull/50#discussion_r961439152 调整。

在代码上避免“先入为主”，无意义的“约定”是不好的习惯，给阅读者和其他工程师造成的门槛。

2022-09-02 09:59 UTC, blackWins commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Application/EasyAbp/WeChatManagement/MiniPrograms/Login/LoginAppService.cs
> +        public virtual async Task BindAsync(BindInput input)
好的，这边继续调整绑定方式。

2022-09-05 09:39 UTC, blackWins commented
逻辑调整为：微信端提交绑定所需数据至 `bind-pre-authorize` ->pc轮询 `pcBindPreAuthorizeInfo` 获取微信提交的数据获取成功停止轮询，->pc确认绑定。

2023-01-06 08:44 UTC, gdlcf88 requested changes

2023-01-06 08:44 UTC, gdlcf88 commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Application/EasyAbp/WeChatManagement/MiniPrograms/Login/LoginAppService.cs
> +        public virtual async Task BindPreAuthorizeAsync(BindPreAuthorizeInput input)
重命名为 `AuthorizePcBindingAsync`

2023-01-06 08:44 UTC, gdlcf88 commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Application/EasyAbp/WeChatManagement/MiniPrograms/Login/LoginAppService.cs
> +        public virtual async Task<BindPreAuthorizeInfoOutput> PcBindPreAuthorizeInfoAsync(BindPreAuthorizeInfoInput input)
重命名为 `GetPcBindingAuthorizationInfoAsync` 或 `GetPcBindingAuthInfoAsync`

2023-01-06 08:44 UTC, gdlcf88 commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Application/EasyAbp/WeChatManagement/MiniPrograms/Login/LoginAppService.cs
> +                return new BindPreAuthorizeInfoOutput() { };
`return new PcBindingAuthorizationInfoOutput();`
或
`return new PcBindingAuthInfoOutput();`

2023-01-06 08:44 UTC, gdlcf88 commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Application/EasyAbp/WeChatManagement/MiniPrograms/Login/LoginAppService.cs
> +            IDistributedCache<MiniProgramPcUserBindPreAuthorizeCacheItem> pcUserBindPreAuthorizeCache,
`IDistributedCache<MiniProgramPcBindingAuthorizationInfoCacheItem> pcBindingAuthorizationInfoCache`
或
`IDistributedCache<MiniProgramPcBindingAuthInfoCacheItem> pcBindingAuthInfoCache`

2023-01-06 08:44 UTC, gdlcf88 commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.HttpApi/EasyAbp/WeChatManagement/MiniPrograms/Login/LoginController.cs
> +        [Route("pc-bind-acode")]
miniProgramName 不可为空，因此可以删除本无用路由

2023-01-06 08:44 UTC, gdlcf88 commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Web/Pages/WeChatManagement/MiniPrograms/Components/WeChatMiniProgramPcBindWidget/Default.cshtml
> +                <h5 id="nickname" style="padding:10px">Freestyle</h5>
为避免网络和程序故障时，用户认为此处内容为真实结果，请使用更安全的默认值，或移除默认值。

2023-01-06 09:14 UTC, gdlcf88 commented
请将主分支(master)合并到本PR分支，并解决冲突。

2023-01-06 10:37 UTC, blackWins commented on modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Application/EasyAbp/WeChatManagement/MiniPrograms/Login/LoginAppService.cs
> +            var hasBound = await _weChatAppUserRepository.AnyAsync(x => x.UserId == CurrentUser.GetId());
hasBound 用于组件判断是显示用户信息ui区域还是显示绑定二维码ui区域

2023-04-14 06:43 UTC, closed without merging